version: '3.1'

services: 
    db:
        image: mongo
        container_name: db
        restart: always
        env_file:
            - .env
        ports:
            - 27017-27019:27017-27019
        environment: 
            MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
            MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
            MONGO_INITDB_DATABASE: ${DB_NAME}
    redis-sv:
        image: redis
        container_name: redis-sv
        restart: always
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        env_file:
            - .env
    api:
        image: node:latest
        container_name: api
        restart: always
        env_file:
            - .env
        depends_on: 
            - db
            - redis-sv
        links:
            - redis-sv
        ports: 
            - ${SERVER_PORT}:${SERVER_PORT}
        volumes: 
            - .:/usr/src/app
        working_dir: /usr/src/app
        command: npm start
        logging: 
            driver: 'json-file'
            options: 
                max-size: '10m'
                max-file: '5'